### ISSUE TITLE
MacOS Automator Cannot Find Z4H, v3

### ISSUE THREAD

**Issue by RickCogley** [romkatv/zsh4humans#44] opened 2020-07-20 09:35 UTC
Hello - I need to run a function from a MacOS automator "run shell script" action. This problem started after I installed z4h, so I hope you don't mind if I ask here. 

The Automator "run shell script" action lets you specify a shell so I select /bin/zsh, but, the environment is apparently not the same as the interactive one. When I first built this automator action, someone on a forum had recommended sourcing the zsh rc files at the top of the "run shell script" action to make sure to get paths and so on, so I did: 

~~~~~
source ~/.zshenv
source ~/.zshrc
my-function #located in .zshrc
~~~~~

This worked fine with my previous setup. Now however, after installing z4h, when running this automator action, I started to get errors that automator "cannot find z4h" when parsing .zshrc. Another forum post recommended exporting PATH so I added that, and also thought I might need FPATH, so I export that too. 

~~~~~
export PATH=/usr/bin:/usr/local/bin:~/.cache/zsh4humans/fzf/bin:~/bin:$PATH
export FPATH=~/.cache/zsh4humans/zsh4humans/fn:~/.cache/zsh4humans/zsh-completions/src:~/bin/zsh/functions:/usr/local/share/zsh/site-functions:$FPATH

source ~/.zshenv
source ~/.zshrc
my-function
~~~~~

This does not work either, and I get: 

> The action "Run Shell Script" encountered an error: "/Users/me/.zshrc:27: command not found z4h

... for two lines in the .zshrc. 

~~~~~
z4h install romkatv/archive romkatv/zsh-prompt-benchmark
z4h init || return
~~~~~

It's getting to the "source" part because the errors reference lines in .zshrc, and apparently it loaded .zshenv ok. 

Is there anything I can try, to make sure this execution environment within Automator will find z4h? 
Any advice appreciated, thanks.

**Comment by romkatv** [comment] 2020-07-20 11:22
> The Automator "run shell script" action lets you specify a shell so I select /bin/zsh, but, the environment is apparently not the same as the interactive one.

What's in the script? How does it fail?

> When I first built this automator action, someone on a forum had recommended sourcing the zsh rc files at the top of the "run shell script" action to make sure to get paths and so on

That's a terrible advice. You should never manually source zsh rc files.

> Another forum post recommended exporting PATH so I added that, and also thought I might need FPATH, so I export that too.

This may or may not be another terrible advice. At this point there simply not enough information to proceed any further. Fixing a broken script requires knowing the content of the script and the error(s) it produces. Knowing how you've tried to fix the problem is useful only after it's clear what the problem is.

**Comment by RickCogley** [comment] 2020-07-20 12:03
Thanks. What's in the script that Automator has in its "run shell script" action is literally this: 

~~~~~
export PATH=/usr/bin:/usr/local/bin:~/.cache/zsh4humans/fzf/bin:~/bin:$PATH
export FPATH=~/.cache/zsh4humans/zsh4humans/fn:~/.cache/zsh4humans/zsh-completions/src:~/bin/zsh/functions:/usr/local/share/zsh/site-functions:$FPATH

source ~/.zshenv
source ~/.zshrc
my-function
~~~~~

It does not even make it to the `my-function` piece, failing while sourcing. When it starts executing the source of .zshrc, it can't find z4h, so I was wondering why, because simply specifying the shell as "/bin/zsh" seems like it should run those rc files as usual (but, apparently not). If I comment the `source` lines, the error is that it fails to find the function. This Automator environment is a bit odd, though, hence the weird hackish advice. 

@romkatv You mentioned the other day about _not_ putting everything in functions, so I'm going to try a different approach, and just migrate the function I'm trying to run, to a shell script, and see if Automator will run that.

**Comment by romkatv** [comment] 2020-07-20 12:08
> It does not even make it to the my-function piece, failing while sourcing.

That's good. Since you are shooting yourself in the foot with `source ~/.zshrc`, the sooner it terminates the less damage you'll suffer.

> @romkatv You mentioned the other day about _not_ putting everything in functions, so I'm going to try a different approach, and just migrate the function I'm trying to run, to a shell script, and see if Automator will run that.

That's the way. You should put in functions what makes no sense as a script. E.g., it makes no sense to turn function `md` into a script because it would be identical to `mkdir`.

I'm going to close the issue as there is nothing to be done in zsh4humans. It does not, should not, and will not support manual sourcing of `~/.zshrc` from scripts.

**Closed by romkatv** 2020-07-20 12:08 UTC

**Comment by RickCogley** [comment] 2020-07-20 12:16
Right, setting automator to use /bin/bash and just specifying a shell script, works as expected.

**Comment by romkatv** [comment] 2020-07-20 12:19
> Right, setting automator to use /bin/bash and just specifying a shell script, works as expected.

Writing scripts in Bash is reasonable. If you prefer writing them in Zsh, that's fine too. Naturally, you can use Perl, Python or anything else. The language in which you write each script is independent from what you use as login shell.
