### ISSUE TITLE
[Question] Where should I put custom completions configurations?

### ISSUE THREAD

**Issue by FaruNL** [romkatv/zsh4humans#123] opened 2021-06-17 13:09 UTC
Specifically, I want zsh to correct me if I mistyped, for example:

`cd down<TAB>`
`cd Downloads`

But I want zsh completion to work even if I put upper case letters in every other place:
`cd dOwN<TAB>`
`cd Downloads`

As well as:
`cd Dwnl<TAB>`
`cd Downloads`

And:
`cd ma.c<TAB>`
`cd main.css`

I think the zsh configuration could be
```
zstyle ':completion:*' completer _complete _approximate
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
```
*(I don't know if `_correct` in the completer is necessary)*

But as the title suggest, idk where to put it.

I tried here, but with no avail:
```
# Define functions and completions.
function md() { [[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1" }
compdef _directories md

# Here
```

**Comment by romkatv** [comment] 2021-06-17 13:11
This is currently not possible unfortunately.

**Comment by FaruNL** [comment] 2021-06-17 13:16
Thanks for the quick reply!

Ok, no problem.
That will be the motivation to type properly then 😀.

Excellent work btw!

**Comment by romkatv** [comment] 2021-06-17 13:17
> Excellent work btw!

Thanks!

**Comment by romkatv** [comment] 2021-06-17 13:17
Closing as I don't intend to work on this (even though the feature request is valid).

**Closed by romkatv** 2021-06-17 13:17 UTC

**Comment by cyklee** [comment] 2021-11-24 02:02
@FaruNL  - I've found adding either lines at the very end of .zshrc seems to work as intended without breaking fzf-completion. However, I have not yet tested this fully. Also, I'm still exploring z4h, so I may have broken other parts without noticing them.

Using this:
`zstyle ':completion:*' matcher-list 'r:|=*' 'l:|=* r:|=*'` 

You will get:
`cd config <TAB>`
`cd .config`

Or, if you want something more aggressive (autocomplete with upper/lower):
```
zstyle ':completion:*' completer _complete _approximate
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
```

You will get:
`cd .Con <TAB>`
`cd .config`
(but `.Con<TAB>` will not work)

**Comment by romkatv** [comment] 2021-11-24 06:22
@cyklee I think both of these break completions in z4h. Sometimes you'll get empty fzf query. Other times you'll get invalid completions altogether.
