### ISSUE TITLE
command-not-found issue directly after installation

### ISSUE THREAD

**Issue by Legisign** [romkatv/zsh4humans#131] opened 2021-07-29 12:17 UTC
After running the installation and configuration, `command-not-found` crashed on Mint 20.2 every time. I found that the database files in `/var/lib/command-not-found` were given 600 permissions, so they couldn’t be read by the regular user. I have `umask` set to 077 in `/etc/login.defs`. `chmod`ding them to 644 fixed the issue.

To check if this is related to zsh4humans, I reverted my VM to a before-installation state and then everything worked fine.

**Comment by romkatv** [comment] 2021-07-29 12:21
zsh4humans isn't installing `/var/lib/command-not-found` and isn't changing the permission of these files (it cannot; it's not a privileged process).

Whatever bricked `command-not-found` on your system wasn't zsh4humans. I'm glad you've managed to fix the issue though.

**Comment by Legisign** [comment] 2021-07-29 12:25
Curious… I have to try the installation again, because I specifically created a new VM snapshot, run the installation, and then got the issue.

**Comment by romkatv** [comment] 2021-07-29 12:28
You ran the installer of zsh4humans as a non-root user, right? And it never asked you to enter your password. So it couldn't have created or changed the permissions of files owned by root.

Is it possible that `command-not-found` was broken on your system but you only found it when zsh4humans tried to utilize it?

**Comment by Legisign** [comment] 2021-07-29 12:35
Yup, I installed as non-root. Something must have enabled the `command-not-found` in between the snapshots because my previous zsh config didn’t use it and now it appears zsh4humans doesn’t enable it either.

Sorry! :)

**Comment by romkatv** [comment] 2021-07-29 12:46
> After running the installation and configuration, `command-not-found` crashed on Mint 20.2 every time
>
> it appears zsh4humans doesn’t enable [`command-not-found`]

How can these two comments be reconciled? If zsh4humans doesn't enable `command-not-found` on your system (this is unexpected by the way; zsh4humans is supposed to utilize `command-not-found` if you have it), how did you observe crashes?

**Comment by Legisign** [comment] 2021-07-29 13:19
I have absolutely no idea! I haven’t even noticed that I haven’t configured zsh in the VM to use `command-not-found` as I’m quite happy to have a simple error message instead of installation suggestions.

Then I created a new snapshot, and without doing anything else installed zsh4humans in it – and bang, typing `ll` crashed Mint’s `command-not-found`. (It’s a collection of Python scripts so troubleshooting took some time.) `ll` is my usual file-listing function but that was of course not present after the installation.  So _something_ must have enabled `command-not-found`, and as the installation was the only thing that I did, I assumed that was it.

**Comment by romkatv** [comment] 2021-07-29 13:46
zsh4humans utilizes `command-not-found` if the latter is installed on your system, so it's not surprising that typing `ll` invokes `command-not-found`. The problem is that `command-not-found` doesn't work on your system. zsh4humans cannot break it, which implies that it was broken to begin with.

Do you get the same error when running the following command?

```zsh
/usr/lib/command-not-found -- ll
```

**Comment by Legisign** [comment] 2021-07-29 13:52
Yup, same results (even under Bash)! So the real culprit is Mint not taking care of permissions in its command database.

That’s actually not even surprising. Changing umask in `/etc/login.defs` to 077 and using `sudo` for something breaks many other systems as well. It looks like many packagers expect everyone stick to whatever umask is the default on the system.

**Comment by romkatv** [comment] 2021-07-29 13:57
> Yup, same results

That's it then.

> (even under Bash)!

This couldn't possibly be otherwise.

Closing as Won't Fix (the issue is with the OS).

**Closed by romkatv** 2021-07-29 13:57 UTC
