### ISSUE TITLE
nix-shell and zsh4humans

### ISSUE THREAD

**Issue by woss** [romkatv/zsh4humans#153] opened 2021-11-01 12:12 UTC
I'm trying to figure out how to enable the zsh4humans when I run the `nix-shell` for a project. I found this on their website but I'm unsure how to do it for this project. https://nixos.wiki/wiki/Zsh

**Comment by romkatv** [comment] 2021-11-01 12:19
I don't know. I don't use nix shell. If you figure it out, please post a comment. I don't intend to research this myself.

**Comment by luxus** [comment] 2021-11-01 18:03
I'm interested in a solution too.. I was thinking to switch maybe to a diy+ (from romkatv benchmark) solution.. but im so happy with z4h it would be great if we find something :D

**Comment by woss** [comment] 2021-11-01 19:02
It seems that the command is pretty straightforward. Although I didn't find how to do it automatically :(

```bash
nix-shell . --command "zsh"
```

This is original zsh + tmux
![image](https://user-images.githubusercontent.com/80440/139723376-98230c0e-e256-40c0-ab7e-e08c25953747.png)

And this is the same but in the `nix-shell`. Notice the `nix impure` after the `Py daniel` ( a python env ) 
![image](https://user-images.githubusercontent.com/80440/139723409-215db6b1-c502-4a00-8c64-c6687f679eae.png)

**Comment by romkatv** [comment] 2021-11-01 19:05
I'm not sure what you mean. Are you saying that you've figured out how to solve the problem? Or perhaps that something is you are seeing is unexpected? If so, what is unexpected what did you expect?

**Comment by woss** [comment] 2021-11-01 19:07
I am saying that i believe i solved it. Basically, z4h is running and when you execute the nix-shell and tell it to use zsh it will load the z4h.

**Comment by woss** [comment] 2021-11-01 19:08
the last screenshot is in the nix-shell. 
![image](https://user-images.githubusercontent.com/80440/139727313-a317d7ac-0056-4940-a3f2-3e8f618310d5.png)

**Comment by romkatv** [comment] 2021-11-01 19:08
Great!

Will future users with the same problem understand how to solve it from your comment? (I'm sorry that I cannot answer this question myself. I know too little about nix to understand either the problem or the solution.)

**Comment by woss** [comment] 2021-11-01 19:09
I have no idea will they, i started using it yesterday :)

**Comment by romkatv** [comment] 2021-11-01 19:10
@luxus Does this help?

**Comment by woss** [comment] 2021-11-01 19:12
Also i found this, https://github.com/chisui/zsh-nix-shell

**Comment by romkatv** [comment] 2021-11-01 19:14
I searched zsh4humans on that page and got no hits. Why do you think it would be useful to me? Recall that I don't use nix. Or perhaps you believe it's relevant to this issue? If so, can you say how?

**Comment by woss** [comment] 2021-11-01 19:18
i don't think there is zsh4humans on that page but there is oh-my-zsh. If I understood correctly that repo is the oh-my-zsh plugin and also I believe I saw oh-my-zsh in the zsh4humans. so I thought they share some similarities and you can maybe either point us how to use it or not 

I mean, I am just providing the info, no need to research or spend you time just for me. If this gets more upvotes and people actually need it then maybe you can do something, since I have no idea how the z4h works internally. 

I hope that answers your question.

**Comment by romkatv** [comment] 2021-11-01 19:21
When you install zsh4humans, your zshrc contains this:

```zsh
# Clone additional Git repositories from GitHub.
#
# This doesn't do anything apart from cloning the repository and keeping it
# up-to-date. Cloned files can be used after `z4h init`. This is just an
# example. If you don't plan to use Oh My Zsh, delete this line.
z4h install ohmyzsh/ohmyzsh || return
```

It's an example of how you can clone repos from github. It's the only connection between zsh4humans and oh-my-zsh.

**Comment by luxus** [comment] 2021-11-01 19:26
I think there is a big misunderstanding here..
nix-shell loads a shell with specific packages (mostly programming langs) . so nix can load specific versions of py or only have rust in a specific folder/shell 
the issue is that running starting nix-shell starts a different shell (I think bash), so there is no z4h in nix-shell
running zsh after starting the shell looks like a dirty fix.
we could try [Lorri](https://github.com/nix-community/lorri) instead of nix-shell
in the release note are some changes about 
`Fix lorri shell for zsh. ZDOTDIR is loaded correctly.`

**Comment by woss** [comment] 2021-11-01 19:30
it could be a misunderstanding on my part. 
as I said I learned about it 2 days ago, and used it in few tutorials yesterday and today. 

What I needed is exactly what I described, all the goodies of my zsh config. I am 100% sure that's NOT proper way but at least I don't have to `ls -lah` all the time ( I have it `lh` )

**Comment by romkatv** [comment] 2021-11-01 19:30
This discussion is way over my head, so I'll let you guys use this space to figure out a solution. If you need to summon me, mention me explicitly.

**Comment by luxus** [comment] 2021-11-01 21:57
@woss  this issue is not related to z4h .. its more a nix-shell issue 
as a solution use https://github.com/nix-community/lorri or https://github.com/nix-community/nix-direnv (has flakes support)

**Comment by romkatv** [comment] 2021-11-02 17:46
Do I understand correctly that you guys have found a satisfactory solution?

**Comment by woss** [comment] 2021-11-02 18:31
well, I am completely fine with the solution that I proposed. It does what I need, BUT what @luxus proposed was something different. 

So, if he doesn't mind I we can close this, and eventually post the correct solution, if and wen we(me) find it. 

To be clear, this is not the `bug` or an `issue` with the z4h, more as a `how do I do it` kind of thing.

**Comment by luxus** [comment] 2021-11-02 18:47
yeah we should close it here... 
its not related to z4h specificly

**Comment by romkatv** [comment] 2021-11-02 18:49
Sounds good to me.

**Closed by romkatv** 2021-11-02 18:49 UTC
