### ISSUE TITLE
z4h update displays "command not found: complete" with google cli completion

### ISSUE THREAD

**Issue by iamhsa** [romkatv/zsh4humans#266] opened 2023-04-13 22:39 UTC
During a `z4h update`, I observe this : 

```zsh
❯ z4h update
z4h: fetching z4h.zsh
z4h: updating zsh4humans
z4h: updating zsh-history-substring-search
z4h: updating zsh-autosuggestions
z4h: updating zsh-completions
z4h: updating zsh-syntax-highlighting
z4h: updating terminfo
z4h: updating fzf
z4h: updating fzf binary
z4h: updating tmux
z4h: updating ohmyzsh/ohmyzsh
z4h: updating powerlevel10k
z4h: updating gitstatus binary
z4h: initializing zsh
/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc:37: command not found: complete
/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc:62: command not found: complete
/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc:63: command not found: complete
z4h: update successful
z4h: restarting zsh
```

I don't know if this is something wrong with the file `completion.zsh.inc` or with zsh4humans.

Reproduce steps (on MacBook)

1. `brew install google-cloud-sdk`
2. `exec zsh`
3. `gcloud <tab> ` **--> not functional**
4. In `~/.zshrc` add this two lines (as almost shown in `brew install` output)
```zsh
z4h source "$HOMEBREW_PREFIX/share/google-cloud-sdk/path.zsh.inc"
z4h source "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.zsh.inc"
```
5. `exec zsh`
6. `gcloud <tab> `  **--> Functional**
7. `z4h update`
8. See `command not found: complete` 3 times on output

**Comment by juangiordana** [comment] 2023-04-14 04:29
I saw this too

complete -o default -F __nvm nvm

**Comment by romkatv** [comment] 2023-04-14 06:11
> ```text
> /opt/homebrew/share/google-cloud-sdk/completion.zsh.inc:37: command not found: complete
> /opt/homebrew/share/google-cloud-sdk/completion.zsh.inc:62: command not found: complete
> /opt/homebrew/share/google-cloud-sdk/completion.zsh.inc:63: command not found: complete
> ```

Thanks for reporting this. Fixed.

> ```zsh
> z4h source "$HOMEBREW_PREFIX/share/google-cloud-sdk/path.zsh.inc"
> ```

Are you sure you need this? Try removing this line, restart your terminal and see if there are any commands you want to run that aren't working. If there are none, you don't need this line. (In general, don't add anything to your zsh startup files unless you can clearly see the positive effect of it.)

> ```zsh
> z4h source "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.zsh.inc"
> ```

This is now automatic. You can remove this line from .zshrc.

**Comment by romkatv** [comment] 2023-04-14 06:12
> I've seen this error too and tracked it down to the NVM completions script:
> 
> https://github.com/nvm-sh/nvm/blob/7b530edd3a2a3ebc976c455394f7245827194da7/bash_completion#L99

If you can describe all steps that lead to the error, I might be able to do something about it.

**Comment by juangiordana** [comment] 2023-04-14 06:45
> If you can describe all steps that lead to an error, I might be able to do something about it.

It used to happen just opening a terminal and running `z4h update` but I didn't reported it because I thought it might have been on my end. I just thought that adding some info to the discussion might help.

Thanks for fixing it.

**Comment by romkatv** [comment] 2023-04-14 06:47
My offer still stands: if you can describe all steps leading to the nvm error, I might be able to fix it.

**Comment by iamhsa** [comment] 2023-04-14 08:52
> Thanks for reporting this. Fixed.

Thanks you for your quick response.

> Are you sure you need this?

I'm pretty sur I don't need it.
It was just to respect `brew install` output

`z4h update`  no longer display `command not found: complete` 👍 

On the other hand, if I remove `z4h source "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.zsh.inc"` from my `~/.zshrc` I no longer have the completions, so for now I keep it.
I suppose, this is something wrong on my side.

**Comment by iamhsa** [comment] 2023-04-14 08:57
In fact, even with `z4h source "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.zsh.inc"` in `~/.zshrc`completion isn't functional.

**Comment by romkatv** [comment] 2023-04-14 09:08
> I'm pretty sur I don't need it. It was just to respect `brew install` output

If doing something was a good default, `brew install` would've done it automatically.

> `z4h update` no longer display `command not found: complete` 👍

Thanks for verifying.

> On the other hand, if I remove `z4h source "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.zsh.inc"` from my `~/.zshrc` I no longer have the completions

Ouch. Fixed.

**Comment by iamhsa** [comment] 2023-04-14 09:21
Works, like a charm!

I let issue open as @juangiordana seem to have a similar issue with nvm

Thank you so much for the quick fix, your time, and advice.

**Comment by romkatv** [comment] 2023-04-14 09:24
> I let issue open as @juangiordana seem to have a similar issue with `nvm`

They haven't submitted an issue report (what they do, what they see and what they expect). They are free to do so in a new issue.

Closing as done.

**Closed by romkatv** 2023-04-14 09:24 UTC

**Comment by juangiordana** [comment] 2023-04-14 11:19
This fixed it.

**Comment by romkatv** [comment] 2023-04-14 12:31
Please open a new issue and describe all steps necessary to reproduce this.
