### ISSUE TITLE
"(eval):zle:1: bad option: -z" when sourcing history-substring-search

### ISSUE THREAD

**Issue by EnacheB** [romkatv/zsh4humans#58] opened 2020-10-24 18:28 UTC
Huge fan of the idea of making a sane default for zsh, btw

When opening a new terminal I get:
`(eval):zle:1: bad option: -z`

I believe the high-level cause of this is adding
`z4h source $Z4H/ohmyzsh/ohmyzsh/plugins/history-substring-search/history-substring-search.zsh`
to my .zshrc

Regular source has the same problem.

Removing the source line and starting a new shell results in a clean start. Does this happen on your machine?

**Comment by romkatv** [comment] 2020-10-24 18:41
Thanks for the report.

If I may ask, why do you want to source that file? What’s lacking if you don’t source it?

**Comment by EnacheB** [comment] 2020-10-24 19:01
Hi, I'm trying to get up-arrow to search for the contents in the whole command (not just the prefix).

For example, if you need to mount a directory, you may type in `mount`, and expect a useful autosuggestion. But you get none, because you forgot to prefix with "sudo". 90% of the time, an up arrow or two will get you the correct command you were looking for `sudo mount relevant-params-here`

I know the alternative would be Ctrl-R, but up arrow is muscle memory for me at this point

i.g.
`bindkey '^[[A' history-substring-search-up`
`bindkey '^[[B' history-substring-search-down`

**Comment by romkatv** [comment] 2020-10-24 19:13
Thanks for the explanation. I'll take a look when I get the time although I have to admit this is not very high priority for me. You've identified the intended solution yourself -- hit <kbd>Ctrl+R</kbd>. This binding performs substring search. If <kbd>Up</kbd> and <kbd>Ctrl+Up</kbd> also performed substring search, they would be less useful.

**Comment by romkatv** [comment] 2020-10-24 19:14
> Edit: Unrelated feedback, where is the history file that zsh4humans uses? I want to prepend the history I had before installing zsh4humans. Doing this automatically / giving the option might improve the experience

It's in `~/.zsh_history`.

> Edit 2: Up arrow triggering the fzf Ctrl-R would be another (possibly better) alternative, but I don't see an easy way to do that from reading the .zshrc

```zsh
z4h bindkey Up z4h-fzf-history
```

This will make it very difficult to edit multi-line commands as you won't be able to move the cursor up.

**Comment by pkazmier** [comment] 2020-10-24 20:12
I upgraded from v2 to v4 (and thus zsh 5.7 to 5.8) today and I had the same error with history-substring-search plugin, which was unfortunate, so I've decided to give fzf another try.

**Comment by romkatv** [comment] 2020-10-25 04:23
> When opening a new terminal I get:
> `(eval):zle:1: bad option: -z`

This is caused by a bug in history-substring-search. I've added a workaround to zsh4humans so that this bug doesn't trigger. This removes the error. However, the search term doesn't get highlighted. This is fixable in theory but unfortunately I don't have the time to fix it right now. Maybe some time later but I don't make any promises.

**Comment by romkatv** [comment] 2020-10-25 04:25
> I've decided to give fzf another try.

Great! Please post feedback on it. I'd like the default UX with the default bindings to be as good as possible. This is the highest priority (unlike support for custom bindings that replace the default widgets in zsh4humans).

**Comment by romkatv** [comment] 2020-11-04 20:36
Closing as the original error has been fixed and I don't intend to fix the lack of highlighting. I might make an attempt to support alternative history and completion UI widgets in the future but not yet.

**Closed by romkatv** 2020-11-04 20:36 UTC
