### ISSUE TITLE
Automatically select suggestion when it's the only one available after filtering the menu and you press TAB

### ISSUE THREAD

**Issue by jmgq** [romkatv/zsh4humans#100] opened 2021-02-22 23:32 UTC
**How to reproduce**
On a fresh installation, if you go to your home folder and type `less .zsh` and then press <kbd>TAB</kbd>, you will be presented with a list with three options:
- `.zshrc`
- `.zshenv`
- `.zsh_history`
Every time you press <kbd>TAB</kbd>, it will highlight the next item, as you would expect. However, if you type the letter `r`, the list of suggestions will be filtered, and the only available option will be `.zshrc`. If you press <kbd>TAB</kbd> again, I would expect `.zshrc` to be automatically selected, since it's the only available option. But instead, nothing happens until you press <kbd>ENTER</kbd>, in which case the option is selected.

**Environment**
This has been tested in an fresh Debian Bullseye (testing) box, using ZSH for Humans v4, as stated in the README.md file in the master branch.

**Comment by romkatv** [comment] 2021-02-23 07:08
This is working as intended. When you press <kbd>Tab</kbd>, what you see isn't just a list of possible completions. It's a selection dialog with built-in search. You can move up and down the list with arrow keys, select multiple items with <kbd>Ctrl+Space</kbd>, and perform multi-token search (tokens are separated by spaces) including anchoring (`txt$` to show only entries that end with `txt`).

**Comment by jmgq** [comment] 2021-02-23 09:40
Thank you for your quick reply (and for the great job you've done in this project!). I understand that this is not a bug, perhaps I should have worded the ticket differently. I was proposing this as an improvement.

Is there any scenario in which you wouldn't want <kbd>TAB</kbd> to behave as <kbd>ENTER</kbd> when there is only one possible suggestion? I cannot think of any.

**Comment by romkatv** [comment] 2021-02-23 09:50
Yes. As I mentioned above, the current behavior is intentional.

On most desktop operating systems you can hit the windows key and search for an app. If at some point you only get one search result, would you want that app to launch automatically?

You can think of many other widgets that use the same UI paradigm. For example, when I type something in the chrome address bar, I get autosuggestions. Sometimes there is only one autosuggestion yet it doesn't get accepted automatically.

Similarly with file managers in Desktop Environments. You can usually type in order to narrow down the list of files in a folder. If there is only one file in the result, it doesn't automatically get chosen (if this was a file choosing dialog) or launched.

**Comment by jmgq** [comment] 2021-02-23 10:06
I agree with all you're saying, but that's not the improvement I'm proposing. I'm not saying that the option should be automatically selected when there is only one option. What I mean is: if you get several options in the menu, then type some letters and the option list gets filtered to just one result, **if you press <kbd>TAB</kbd> when there is only one result**, that result should be selected. Does that make sense?

This behaviour that I'm describing is very common and basic. That's how it normally works in `bash` or `zsh`. If you're in the command line and start typing, when you press <kbd>TAB</kbd> it will automatically autocomplete as many letters as possible, when there is no ambiguity.

I hope this makes it more clear, it's a bit hard to explain, to be honest.

**Comment by romkatv** [comment] 2021-02-23 10:13
> I agree with all you're saying, but that's not the improvement I'm proposing. I'm not saying that the option should be automatically selected when there is only one option. What I mean is: if you get several options in the menu, then type some letters and the option list gets filtered to just one result, **if you press TAB when there is only one result**, that result should be selected. Does that make sense?

If there is more than one element in the list, you want <kbd>Tab</kbd> to behave like <kbd>Down</kbd> but if there is only one element, you want <kbd>Tab</kbd> to behave like <kbd>Enter</kbd>? Did I understand you correctly?

> This behaviour that I'm describing is very common and basic. That's how it normally works in `bash` or `zsh`.

Neither bash nor zsh have a search widget of this kind. The closest they have is <kbd>Ctrl+R</kbd>. Note that this widget doesn't auto-close when there is only one match. You still need to press <kbd>Enter</kbd>.

I don't know of any application that would close the search dialog when there is only one match.

**Comment by jmgq** [comment] 2021-02-23 11:08
> If there is more than one element in the list, you want <kbd>Tab</kbd> to behave like <kbd>Down</kbd> but if there is only one element, you want <kbd>Tab</kbd> to behave like <kbd>Enter</kbd>? Did I understand you correctly?

That's what I meant, yes :-)

The reason why I thought it would be more natural that way is because, if we go back to my original example, providing that we're not using ZSH for Humans and, instead, we're just using plain zsh (or even bash), when I type `less .zsh` and hit <kbd>TAB</kbd>, I would get three suggestions (`.zshrc`, `.zshenv` and `.zsh_history`). If I now type `r` and press <kbd>TAB</kbd>, it will autocomplete to `.zshrc`. This is the default behaviour when there are no plugins or frameworks installed. I hope that made sense.

**Comment by romkatv** [comment] 2021-02-23 11:22
> > If there is more than one element in the list, you want Tab to behave like Down but if there is only one element, you want Tab to behave like Enter? Did I understand you correctly?
> 
> That's what I meant, yes :-)

Thanks for confirming. It's not something I'm willing to implement even as an optional feature.

> The reason why I thought it would be more natural that way is because, if we go back to my original example, providing that we're not using ZSH for Humans and, instead, we're just using plain zsh (or even bash), when I type `less .zsh` and hit TAB, I would get three suggestions (`.zshrc`, `.zshenv` and `.zsh_history`). If I now type `r` and press TAB, it will autocomplete to `.zshrc`. This is the default behaviour when there are no plugins or frameworks installed. I hope that made sense.

It makes sense, because there is no search dialog. After you press <kbd>Tab</kbd> and see the list of options, all keys are still handled by `readline` (in case of bash) or `zle` (zsh), like before. Zsh for Humans uses a different UI, with a modal dialog that allows you to search.

Closing as Won't Fix.

**Closed by romkatv** 2021-02-23 11:22 UTC
